base: Add missing ActivityStarter class
FAILED: //frameworks/base/packages/SystemUI:SystemUI-core turbine apt
Outputs: out/soong/.intermediates/frameworks/base/packages/SystemUI/SystemUI-core/android_common/kapt/kapt-sources.jar out/soong/.intermediates/frameworks/base/packages/SystemUI/SystemUI-core/android_common/kapt/kapt-res.jar
Error: exited with code: 1
Command: prebuilts/jdk/jdk21/linux-x86/bin/java -XX:OnError="cat hs_err_pid%p.log" -XX:CICompilerCount=6 -XX:+UseDynamicNumberOfGCThreads -jar out/host/linux-x86/framework/turbine.jar --gensrc_output out/soong/.intermediates/frameworks/base/>
Output:
frameworks/base/packages/SystemUI/src/com/android/systemui/Dependency.java:164: error: could not resolve ActivityStarter
    @Inject Lazy<ActivityStarter> mActivityStarter;
                 ^
<>: error: InjectProcessingStep was unable to process 'mDumpManager' because 'ActivityStarter' could not be resolved.

Dependency trace:
    => element (CLASS): com.android.systemui.Dependency
    => element (FIELD): mActivityStarter
    => type (DECLARED field type): dagger.Lazy<ActivityStarter>
    => type (ERROR type argument): ActivityStarter

If type 'ActivityStarter' is a generated type, check above for compilation errors that may have prevented the type from being generated. Otherwise, ensure that type 'ActivityStarter' is on your classpath.
Signed-off-by: GuidixX <guidixm@gmail.com>